version: '3'
services:
  tx-sitter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - blockchain
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TX_SITTER__SERVICE__ESCALATION_INTERVAL=1m
      - TX_SITTER__DATABASE__KIND=connection_string
      - TX_SITTER__DATABASE__CONNECTION_STRING=postgres://postgres:postgres@db:5432/tx-sitter?sslmode=disable
      - TX_SITTER__KEYS__KIND=local
      - TX_SITTER__SERVICE__PREDEFINED__NETWORK__CHAIN_ID=31337
      - TX_SITTER__SERVICE__PREDEFINED__NETWORK__NAME=Anvil
      - TX_SITTER__SERVICE__PREDEFINED__NETWORK__HTTP_RPC=http://blockchain:8545
      - TX_SITTER__SERVICE__PREDEFINED__NETWORK__WS_RPC=ws://blockchain:8545
      - TX_SITTER__SERVICE__PREDEFINED__RELAYER__ID=1b908a34-5dc1-4d2d-a146-5eb46e975830
      - TX_SITTER__SERVICE__PREDEFINED__RELAYER__NAME=Relayer
      - TX_SITTER__SERVICE__PREDEFINED__RELAYER__CHAIN_ID=31337
      # Test only local relayer key id - i.e. the private key associated with the 0x1d7ffed610cc4cdC097ecDc835Ae5FEE93C9e3Da address
      - TX_SITTER__SERVICE__PREDEFINED__RELAYER__KEY_ID=d10607662a85424f02a33fb1e6d095bd0ac7154396ff09762e41f82ff2233aaa
      # Test only API KEY - used for local deployments & testing
      - TX_SITTER__SERVICE__PREDEFINED__RELAYER__API_KEY=G5CKNF3BTS2hRl60bpdYMNPqXvXsP-QZd2lrtmgctsk=
      - TX_SITTER__SERVER__HOST=0.0.0.0:3000
      - TX_SITTER__SERVER__DISABLE_AUTH=true
      - RUST_LOG=info

  db:
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  blockchain:
    hostname: blockchain
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    command: ["anvil --block-time 2 --host 0.0.0.0"]

  # blockchain:
  #   image: ethereum/client-go:alltools-stable
  #   hostname: blockchain
  #   command: >
  #     geth --datadir /root/datadir --dev --http --ws
  #     --http.api eth,web3,net,debug
  #     --http.addr "0.0.0.0"
  #     --ws.addr "0.0.0.0"
  #     --ws.port 8545
  #     --http.vhosts "*"
  #     --http.corsdomain "https://remix.ethereum.org"
  #     --rpc.gascap 0
  #     --rpc.txfeecap 0
  #     --vmdebug
  #   volumes:
  #     - geth_datadir:/root/datadir
  #   ports:
  #     - "30303:30303"
  #     - "8545:8545"
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped

# volumes:
#   geth_datadir: