name: Update dev deployment

on:
  push:
    branches:
      - main

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          repository: worldcoin/tx-sitter-monolith-deploy
          event-type: update-dev
          client-payload: |
            {
              "ref": "${{ github.sha }}",
              "issuer":  "${{ steps.PR.outputs.pr_url }}"
            }
